# conda env create -f environment.yaml ; conda activate cgx_code
name: cgx_code

channels:
  - conda-forge

dependencies:
  - python=3.12.0
  - pip
  - numpy=1.26.2
  - matplotlib=3.8.2
  - pandas=2.1.4
  - sqlalchemy=2.0.29
  - flask=3.0.2
  - requests=2.31.0
  - pip:
  # For regular pip packages
    - flask_sqlalchemy==3.1.1
    - pycoingecko==3.1.0
    - yfinance==0.2.37